import React from 'react';
import { Box, Paper, Typography } from '@mui/material';

function Plan() {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        alignItems: 'center',
        justifyContent: 'center',
        bgcolor: 'background.default',
        color: 'text.primary',
        p: 3,
      }}
    >
      <Paper
        elevation={0}
        sx={{
          p: 3,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          width: '100%',
          maxWidth: 480,
          mt: 4,
        }}
      >
        <Typography
          variant="h4"
          component="h1"
          gutterBottom
          align="center"
          sx={{
            fontWeight: 700,
            fontSize: '2.4rem',
          }}
        >
          Your Step-by-Step Plan
        </Typography>
        <Typography
          variant="body1"
          align="center"
          sx={{ fontSize: '1.25rem', mt: 2, mb: 4 }}
        >
          {/* Display the plan generated by OpenAI here */}
          Step 1: Do this
          <br />
          Step 2: Do that
          <br />
          Step 3: And so on...
        </Typography>
      </Paper>
    </Box>
  );
}

export default Plan;
